//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	in.Envoy.DeepCopyInto(&out.Envoy)
	in.Keycloak.DeepCopyInto(&out.Keycloak)
	if in.RealmUsers != nil {
		in, out := &in.RealmUsers, &out.RealmUsers
		*out = make([]RealmUser, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapAdminSpec) DeepCopyInto(out *BootstrapAdminSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapAdminSpec.
func (in *BootstrapAdminSpec) DeepCopy() *BootstrapAdminSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheAuthSpec) DeepCopyInto(out *CacheAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheAuthSpec.
func (in *CacheAuthSpec) DeepCopy() *CacheAuthSpec {
	if in == nil {
		return nil
	}
	out := new(CacheAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheConfig) DeepCopyInto(out *CacheConfig) {
	*out = *in
	if in.Deploy != nil {
		in, out := &in.Deploy, &out.Deploy
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	out.Auth = in.Auth
	out.TLS = in.TLS
	in.Persistence.DeepCopyInto(&out.Persistence)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConfig.
func (in *CacheConfig) DeepCopy() *CacheConfig {
	if in == nil {
		return nil
	}
	out := new(CacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachePersistenceSpec) DeepCopyInto(out *CachePersistenceSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachePersistenceSpec.
func (in *CachePersistenceSpec) DeepCopy() *CachePersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(CachePersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTLSSpec) DeepCopyInto(out *CacheTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTLSSpec.
func (in *CacheTLSSpec) DeepCopy() *CacheTLSSpec {
	if in == nil {
		return nil
	}
	out := new(CacheTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerySpec) DeepCopyInto(out *CelerySpec) {
	*out = *in
	in.Workers.DeepCopyInto(&out.Workers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerySpec.
func (in *CelerySpec) DeepCopy() *CelerySpec {
	if in == nil {
		return nil
	}
	out := new(CelerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryWorkerSpec) DeepCopyInto(out *CeleryWorkerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryWorkerSpec.
func (in *CeleryWorkerSpec) DeepCopy() *CeleryWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(CeleryWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryWorkersSpec) DeepCopyInto(out *CeleryWorkersSpec) {
	*out = *in
	in.Default.DeepCopyInto(&out.Default)
	in.Priority.DeepCopyInto(&out.Priority)
	in.Summary.DeepCopyInto(&out.Summary)
	in.OCP.DeepCopyInto(&out.OCP)
	in.CostModel.DeepCopyInto(&out.CostModel)
	in.Refresh.DeepCopyInto(&out.Refresh)
	in.HCS.DeepCopyInto(&out.HCS)
	in.Download.DeepCopyInto(&out.Download)
	in.SubsExtraction.DeepCopyInto(&out.SubsExtraction)
	in.SubsTransmission.DeepCopyInto(&out.SubsTransmission)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryWorkersSpec.
func (in *CeleryWorkersSpec) DeepCopy() *CeleryWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(CeleryWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostManagementConfig) DeepCopyInto(out *CostManagementConfig) {
	*out = *in
	if in.ScheduleReportChecks != nil {
		in, out := &in.ScheduleReportChecks, &out.ScheduleReportChecks
		*out = new(bool)
		**out = **in
	}
	out.Storage = in.Storage
	in.API.DeepCopyInto(&out.API)
	in.Masu.DeepCopyInto(&out.Masu)
	in.Listener.DeepCopyInto(&out.Listener)
	in.Celery.DeepCopyInto(&out.Celery)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostManagementConfig.
func (in *CostManagementConfig) DeepCopy() *CostManagementConfig {
	if in == nil {
		return nil
	}
	out := new(CostManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostManagementServiceConfig) DeepCopyInto(out *CostManagementServiceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostManagementServiceConfig.
func (in *CostManagementServiceConfig) DeepCopy() *CostManagementServiceConfig {
	if in == nil {
		return nil
	}
	out := new(CostManagementServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostManagementServiceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostManagementServiceConfigList) DeepCopyInto(out *CostManagementServiceConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostManagementServiceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostManagementServiceConfigList.
func (in *CostManagementServiceConfigList) DeepCopy() *CostManagementServiceConfigList {
	if in == nil {
		return nil
	}
	out := new(CostManagementServiceConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostManagementServiceConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostManagementServiceConfigSpec) DeepCopyInto(out *CostManagementServiceConfigSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	in.Database.DeepCopyInto(&out.Database)
	in.Cache.DeepCopyInto(&out.Cache)
	out.Kafka = in.Kafka
	in.ObjectStorage.DeepCopyInto(&out.ObjectStorage)
	in.Auth.DeepCopyInto(&out.Auth)
	in.RBAC.DeepCopyInto(&out.RBAC)
	in.CostManagement.DeepCopyInto(&out.CostManagement)
	in.ROS.DeepCopyInto(&out.ROS)
	in.Kruize.DeepCopyInto(&out.Kruize)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.UI.DeepCopyInto(&out.UI)
	in.GatewayRoute.DeepCopyInto(&out.GatewayRoute)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostManagementServiceConfigSpec.
func (in *CostManagementServiceConfigSpec) DeepCopy() *CostManagementServiceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CostManagementServiceConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostManagementServiceConfigStatus) DeepCopyInto(out *CostManagementServiceConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredConfig != nil {
		in, out := &in.DiscoveredConfig, &out.DiscoveredConfig
		*out = new(DiscoveredConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostManagementServiceConfigStatus.
func (in *CostManagementServiceConfigStatus) DeepCopy() *CostManagementServiceConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CostManagementServiceConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostManagementStorageSpec) DeepCopyInto(out *CostManagementStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostManagementStorageSpec.
func (in *CostManagementStorageSpec) DeepCopy() *CostManagementStorageSpec {
	if in == nil {
		return nil
	}
	out := new(CostManagementStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.Deploy != nil {
		in, out := &in.Deploy, &out.Deploy
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStorageSpec) DeepCopyInto(out *DatabaseStorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStorageSpec.
func (in *DatabaseStorageSpec) DeepCopy() *DatabaseStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredConfig) DeepCopyInto(out *DiscoveredConfig) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(DiscoveredS3)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredConfig.
func (in *DiscoveredConfig) DeepCopy() *DiscoveredConfig {
	if in == nil {
		return nil
	}
	out := new(DiscoveredConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredS3) DeepCopyInto(out *DiscoveredS3) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredS3.
func (in *DiscoveredS3) DeepCopy() *DiscoveredS3 {
	if in == nil {
		return nil
	}
	out := new(DiscoveredS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoySpec) DeepCopyInto(out *EnvoySpec) {
	*out = *in
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoySpec.
func (in *EnvoySpec) DeepCopy() *EnvoySpec {
	if in == nil {
		return nil
	}
	out := new(EnvoySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRouteConfig) DeepCopyInto(out *GatewayRouteConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRouteConfig.
func (in *GatewayRouteConfig) DeepCopy() *GatewayRouteConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressConfig) DeepCopyInto(out *IngressConfig) {
	*out = *in
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressConfig.
func (in *IngressConfig) DeepCopy() *IngressConfig {
	if in == nil {
		return nil
	}
	out := new(IngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConfig) DeepCopyInto(out *KafkaConfig) {
	*out = *in
	out.SASL = in.SASL
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConfig.
func (in *KafkaConfig) DeepCopy() *KafkaConfig {
	if in == nil {
		return nil
	}
	out := new(KafkaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSASLSpec) DeepCopyInto(out *KafkaSASLSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSASLSpec.
func (in *KafkaSASLSpec) DeepCopy() *KafkaSASLSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSASLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTLSSpec) DeepCopyInto(out *KafkaTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTLSSpec.
func (in *KafkaTLSSpec) DeepCopy() *KafkaTLSSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakSpec) DeepCopyInto(out *KeycloakSpec) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakSpec.
func (in *KeycloakSpec) DeepCopy() *KeycloakSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakSyncSpec) DeepCopyInto(out *KeycloakSyncSpec) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakSyncSpec.
func (in *KeycloakSyncSpec) DeepCopy() *KeycloakSyncSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakTLSSpec) DeepCopyInto(out *KeycloakTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakTLSSpec.
func (in *KeycloakTLSSpec) DeepCopy() *KeycloakTLSSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KokuAPISpec) DeepCopyInto(out *KokuAPISpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KokuAPISpec.
func (in *KokuAPISpec) DeepCopy() *KokuAPISpec {
	if in == nil {
		return nil
	}
	out := new(KokuAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KruizeConfig) DeepCopyInto(out *KruizeConfig) {
	*out = *in
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
	in.Partitions.DeepCopyInto(&out.Partitions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KruizeConfig.
func (in *KruizeConfig) DeepCopy() *KruizeConfig {
	if in == nil {
		return nil
	}
	out := new(KruizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KruizePartitionsSpec) DeepCopyInto(out *KruizePartitionsSpec) {
	*out = *in
	if in.CreateEnabled != nil {
		in, out := &in.CreateEnabled, &out.CreateEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEnabled != nil {
		in, out := &in.DeleteEnabled, &out.DeleteEnabled
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KruizePartitionsSpec.
func (in *KruizePartitionsSpec) DeepCopy() *KruizePartitionsSpec {
	if in == nil {
		return nil
	}
	out := new(KruizePartitionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerSpec) DeepCopyInto(out *ListenerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerSpec.
func (in *ListenerSpec) DeepCopy() *ListenerSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasuSpec) DeepCopyInto(out *MasuSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasuSpec.
func (in *MasuSpec) DeepCopy() *MasuSpec {
	if in == nil {
		return nil
	}
	out := new(MasuSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthProxySpec) DeepCopyInto(out *OAuthProxySpec) {
	*out = *in
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthProxySpec.
func (in *OAuthProxySpec) DeepCopy() *OAuthProxySpec {
	if in == nil {
		return nil
	}
	out := new(OAuthProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageConfig) DeepCopyInto(out *ObjectStorageConfig) {
	*out = *in
	if in.UseSSL != nil {
		in, out := &in.UseSSL, &out.UseSSL
		*out = new(bool)
		**out = **in
	}
	out.S3 = in.S3
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageConfig.
func (in *ObjectStorageConfig) DeepCopy() *ObjectStorageConfig {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACComponentSpec) DeepCopyInto(out *RBACComponentSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACComponentSpec.
func (in *RBACComponentSpec) DeepCopy() *RBACComponentSpec {
	if in == nil {
		return nil
	}
	out := new(RBACComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACConfig) DeepCopyInto(out *RBACConfig) {
	*out = *in
	out.Image = in.Image
	in.API.DeepCopyInto(&out.API)
	in.Worker.DeepCopyInto(&out.Worker)
	out.BootstrapAdmin = in.BootstrapAdmin
	in.KeycloakSync.DeepCopyInto(&out.KeycloakSync)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACConfig.
func (in *RBACConfig) DeepCopy() *RBACConfig {
	if in == nil {
		return nil
	}
	out := new(RBACConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSAPISpec) DeepCopyInto(out *ROSAPISpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSAPISpec.
func (in *ROSAPISpec) DeepCopy() *ROSAPISpec {
	if in == nil {
		return nil
	}
	out := new(ROSAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSConfig) DeepCopyInto(out *ROSConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	in.API.DeepCopyInto(&out.API)
	in.Processor.DeepCopyInto(&out.Processor)
	in.RecommendationPoller.DeepCopyInto(&out.RecommendationPoller)
	in.Housekeeper.DeepCopyInto(&out.Housekeeper)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSConfig.
func (in *ROSConfig) DeepCopy() *ROSConfig {
	if in == nil {
		return nil
	}
	out := new(ROSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSHousekeeperSpec) DeepCopyInto(out *ROSHousekeeperSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.PartitionCleaner.DeepCopyInto(&out.PartitionCleaner)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSHousekeeperSpec.
func (in *ROSHousekeeperSpec) DeepCopy() *ROSHousekeeperSpec {
	if in == nil {
		return nil
	}
	out := new(ROSHousekeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSPartitionCleanerSpec) DeepCopyInto(out *ROSPartitionCleanerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSPartitionCleanerSpec.
func (in *ROSPartitionCleanerSpec) DeepCopy() *ROSPartitionCleanerSpec {
	if in == nil {
		return nil
	}
	out := new(ROSPartitionCleanerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSPollerSpec) DeepCopyInto(out *ROSPollerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSPollerSpec.
func (in *ROSPollerSpec) DeepCopy() *ROSPollerSpec {
	if in == nil {
		return nil
	}
	out := new(ROSPollerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSProcessorSpec) DeepCopyInto(out *ROSProcessorSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSProcessorSpec.
func (in *ROSProcessorSpec) DeepCopy() *ROSProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(ROSProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmUser) DeepCopyInto(out *RealmUser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmUser.
func (in *RealmUser) DeepCopy() *RealmUser {
	if in == nil {
		return nil
	}
	out := new(RealmUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteTLSSpec) DeepCopyInto(out *RouteTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteTLSSpec.
func (in *RouteTLSSpec) DeepCopy() *RouteTLSSpec {
	if in == nil {
		return nil
	}
	out := new(RouteTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Options) DeepCopyInto(out *S3Options) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Options.
func (in *S3Options) DeepCopy() *S3Options {
	if in == nil {
		return nil
	}
	out := new(S3Options)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIAppSpec) DeepCopyInto(out *UIAppSpec) {
	*out = *in
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIAppSpec.
func (in *UIAppSpec) DeepCopy() *UIAppSpec {
	if in == nil {
		return nil
	}
	out := new(UIAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIConfig) DeepCopyInto(out *UIConfig) {
	*out = *in
	in.OAuthProxy.DeepCopyInto(&out.OAuthProxy)
	in.App.DeepCopyInto(&out.App)
	out.OAuthClientSecretRef = in.OAuthClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIConfig.
func (in *UIConfig) DeepCopy() *UIConfig {
	if in == nil {
		return nil
	}
	out := new(UIConfig)
	in.DeepCopyInto(out)
	return out
}
